#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'breakingRecords' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY scores as parameter.
#

def breakingRecords(scores):
    
    Maximum = scores[0]
    Minimum = scores[0]
    Min = 0
    Max = 0
    maxRecordBreak = 0
    minRecordBreak = 0
    for score in scores:
        if score>Maximum:
            Max = Max + 1
            Maximum = score
            maxRecordBreak = maxRecordBreak + 1
        if score < Minimum:
            Min = Min + 1
            Minimum = score
            minRecordBreak = minRecordBreak + 1
    return   maxRecordBreak , minRecordBreak 

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
