#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    zeros = 0
    negatives = 0
    positives = 0
    for number in arr:
        if number == 0:
            zeros = zeros + 1
        if number<0:
            negatives = negatives + 1
        if number>0:
            positives = positives + 1
    print("{:.6f}".format(positives/n))
    print("{:.6f}".format(negatives/n))
    print("{:.6f}".format(zeros/n))
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
