#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    
    first_2_digits = int(s[:2])
    if s[-2:] == "PM" and s[:2] == "12":    
        time =   s[0:-2]
    if s[-2:] == "PM" and  s[:2]!="12":
        first_2_digits = first_2_digits + 12
        time = str(first_2_digits) + s[2:-2]  
    if s[-2:] == "AM" and s[:2]=="12":
        time = "00" + s[2:-2]  
    if s[-2:] == "AM" and s[:2]!="12":
        time = s[:-2]
    return time
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
